---
title: "Style Guide"
author: "Subhajit Chattopadhyay"
date: "4/20/2020"
output: html_document
---
<p>Every language has its DOs and DONTs. So as a language R also has some guidelines as how codes should be written. 

There is a package called formatR. which can be used to correct badly written codes , but it can not completely correct all the mistakes.</p>

<p>Brief guidelines will be provided in the following issues :

<ul>
<li> Naming </li>

<li> Syntax </li>

</ul>

### File Names ###

File names should be relevant and meaningful and should end with ".R" extension.

***Good Example:***

sales_analysis.R

***Bad Example***

foo.r

If the files need to run in a particular sequence then prefix with numbers:

0-file1.R
1-file2.R
2-file3.R

### Object Names ###

<ul>

<li> It is to be rememberered that the Variables and Functions should be is Lower Case. </li>

<li> Use (_) to seprate words within a name. </li>

<li> Generally , for ease of identification Objects' name should "Nouns". </li>

<li> And the names of the functions should be "Verbs".</li>



<li>AVOID using names existing Key Words of R (existing functions and variables). This will create confusion.<li>

</ul>
***Good Examples***

day_one
day_1

month_sales

***Bad Examples***

first_day_of_the_month

DayOne

dayone


T <- FALSE [ "T" stands for logical value True and "F" stands for FALSE ]. 

mean <- function(x)sum(x)

[mean is a standard function of Base package. This implies "Average".]


### Spacing ###

<p> There should be space arounf all ooperators like (+,-,=, <-).</p>


### Curly braces ###

An opening curly brace should never go on its own line and should always be followed by a new line.

### Identation ###
 Two space , tabs not to be used.

### Commenting ###

***(#)*** is used for commenting. The length of the commneting line prefereably belimited to 80 characters.

